### ISSUE TITLE
No License File

### ISSUE THREAD

**Issue by jacobhuesman** [jaredfin/SikuliXRobotLibrary#2]
What License is this under? This is a great library and I'd love to use it in some projects.

**Comment by jaredfin** [comment]
hi jake, i'm not really familiar with the process with licensing. however, this is open source. you may use, edit or expand the library to your liking.
i think some of my codes still needs to be optimized. i still am a beginner in python. this library is reversed engineer from the library shared by my mike in his blog: http://blog.mykhailo.com/2011/02/how-to-sikuli-and-robot-framework.html.

**Comment by jacobhuesman** [comment]
Most people just include a license file in the root directory of their project. I've included an example of the MIT License, a pretty common one that describes the permissiveness you are describing.
[LICENSE.txt](https://github.com/jaredfin/SikuliXRobotLibrary/files/126502/LICENSE.txt)
If you need help deciding, GitHub has a really good website: https://help.github.com/articles/open-source-licensing/ and http://choosealicense.com/.

**Comment by jaredfin** [comment]
i added a license file. thank you.

**Comment by jacobhuesman** [comment]
Thanks!
