### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by kbesser** [jaredfin/SikuliXRobotLibrary#3]
I am receiving an ImportError telling me there is no module named _text_recognition

I have searched through the files and cannot find the module. Is there something missing or something that I am failing to do during setup? I am running Jython 2.7.0 and do a jython setup.py install in terminal.

**Comment by jaredfin** [comment]
i forgot to update the documentation. You need to add the following in your environment variables.

JYTHONPATH
C:<path or folder containing the api.jar>\sikulixapi.jar\Lib;C:<path or folder containing the api.jar>\sikulixapi.jar\org

CLASSPATH
C:<path or folder containing the api.jar>\sikulixapi.jar
